/*
   Copyright 2013 Vastech SA (PTY) LTD

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package main

//File generated by Gradle build. Do not edit
const generatedMajor = "0"
const generatedMinor = "6"
const generatedRelease = "2"
const generatedGitHash = "de8d06baeab734a93ce36032d283c852de5d394e"
